version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practice, because Windows line endings are different from Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
environment:
  COVERALLS_REPO_TOKEN:
    secure: sgK787WUM0FNU200KHy/g4iHpLSGqw9yHWUomz2TWT1PNGiU6vpGjnqwgqdJBFfz
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd : dotnet restore ./WebAPI/WebAPI.csproj --verbosity m
build_script:
  # output will be in ./WebAPI/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./WebAPI/WebAPI.csproj  
after_build:
 # for once the build has completed
artifacts:
  - path: '\WebAPI\bin\Debug\netcoreapp1.1\publish'
    name: Website
    type: WebDeployPackage
clone_depth: 1
test_script:  
- ps: >-
    $resultsFile = $ENV:APPVEYOR_BUILD_FOLDER + '\results.xml';  
    $openCoverConsole = $ENV:USERPROFILE + '\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe';
    $target = '-target:C:\Program Files\dotnet\dotnet.exe';
    $targetArgs = '-targetargs: test ' + $ENV:APPVEYOR_BUILD_FOLDER + '\WebAPITests -c ' + $ENV:CONFIGURATION;
    $filter = '-filter:+[WebAPI*]* -[WebAPI]*' & $openCoverConsole $target $targetArgs '-register:user' $filter '-oldStyle';       
on_finish:
  # any cleanup in here
deploy: off
  
  
