version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Good practice, because Windows line endings are different from Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
environment:
  COVERALLS_REPO_TOKEN:
    secure: sgK787WUM0FNU200KHy/g4iHpLSGqw9yHWUomz2TWT1PNGiU6vpGjnqwgqdJBFfz
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd : dotnet restore ./WebAPI/WebAPI.csproj --verbosity m
build_script:
  # output will be in ./WebAPI/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./WebAPI/WebAPI.csproj  
after_build:
 # for once the build has completed
artifacts:
  - path: '\WebAPI\bin\Debug\netcoreapp1.1\publish'
    name: Website
    type: WebDeployPackage
clone_depth: 1
test_script:  
- ps: >-
    dotnet restore;
    nuget restore;
    dotnet restore --packages .\packages;
    nuget restore -PackagesDirectory .\packages;
    dotnet publish .\WebAPITests -o ..\build_tests --framework netcoreapp1.1;
    ls;   
    .\packages\opencover\4.6.519\tools\OpenCover.Console.exe -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"vstest WebAPITests.dll" -targetdir:"build_tests" -oldStyle -register:user -output:"_CodeCoverageResult.xml" -filter:"+[WebAPI]*";
    .\packages\ReportGenerator\2.5.10\tools\ReportGenerator.exe "-reports:_CodeCoverageResult.xml" "-targetdir:_CodeCoverageReport";    
    .\packages\coveralls.net\0.7.0\tools\csmacnz.Coveralls.exe  --opencover -i .\_CodeCoverageResult.xml --useRelativePaths;
on_finish:
  # any cleanup in here
deploy:
  provider: WebDeploy
  server: dotnetcoresampelwebapp.scm.azurewebsites.net:443
  website: dotnetcoresampelwebapp
  username: manishb123
  password: chnJChiTe7HptfS6RhMa1ilxcdPSptSdxsdSmEAp1wrM3AbyXlgFD24fuwmD 
  NTLM: disabled
  
